[alias]
wasm        = "build --release --lib --target wasm32-unknown-unknown"
schema      = "run --bin schema"
unit-test   = "test --lib"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-arg=-s",
  "-C", "link-arg=--import-undefined",
]
