[package]
name = "aegis-near"
version = "0.2.0"
edition = "2021"
description = "Aegis CCHS-S-20 post-quantum smart account for NEAR"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk  = "5.5"
cchs-core = { path = "../cchs-core", default-features = false }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[workspace]
